import Head from "next/head";
import Header from "../src/components/header/header.js";
import Footer from "../src/components/footer/footer.js";
// import CardIndex from "./../../src/components/cards_index/cards_index.js";
import styles from "../public/assets/styles/index.module.css";
import CardAbout from "../src/components/card_about/card.about..js";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Fortlog Transportes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="assets/images/logos/logo_fortlog_cortada.png" />
      </Head>

      <main>
        {/*Aqui chamamos o componente header, que será utilizado em todas as páginas da aplicação*/}
        <Header />
        <div className={styles.historia}>
          <p className={styles.title}>História da Empresa</p>
          <p>
            A Fortlog foi criada em 2019 para atender serviços logísticos em
            todo estado do Ceará e Piauí, atendendo a mais de 1.000 clientes no
            total
          </p>
        </div>
        <div className={styles.card}>
          <p className={styles.title}>Missão | Visão | Valores</p>
          <p>
            A Fortlog foi criada em 2019 para atender serviços logísticos em
            todo estado do Ceará e Piauí, atendendo a mais de 1.000 clientes no
            total
          </p>
          <CardAbout />
          <CardAbout />
          <CardAbout />
        </div>
        <div className={styles.historia}>
          <p className={styles.title}>Equipe</p>
          <p>
            Equipe profissional, treinada e capacitada para agir em diversos
            tipos de ambiente
          </p>
        </div>
        <div className={styles.historia}>
          <p className={styles.title}>Parceiros</p>
          <p>Confira nossos parceiros e clientes!</p>
        </div>
        <div className={styles.historia}>
          <p className={styles.title}>Localização</p>
          <p>
            Travessa José Bastos 79
          </p>
        </div>
        {/*Aqui chamamos o componente footer, que será utilizado em todas as páginas da aplicação*/}
        <Footer />
      </main>
    </div>
  );
}
