import Head from "next/head";
import Header from "./../components/_ui/header/header";
import Footer from "./../components/_ui/footer/footer";
import CardAbout from "./../components/About/Cards/card_about";
import styles from "./../styles/about.module.css";
import CardHistory from "../components/About/CardHistory/card_history";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Fortlog Transportes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="assets/images/logos/logo_fortlog_cortada.png" />
      </Head>

      <main>
        {/*Aqui chamamos o componente header, que será utilizado em todas as páginas da aplicação*/}
        <Header />
        <div className={styles.historia}>
          <p className={styles.title}>Nossa História</p>
          <CardHistory/>
        </div>

        <div className={styles.missao}>
          <div className={styles.title}>
            <p>Focados em entregar o melhor!</p>
          </div>
          <div className={styles.cards}>
            <CardAbout
              title="Missão"
              subtitle="Conheça nossa Missão!"
              text="Nossa missão é.."
            />
            <CardAbout
              title="Visão"
              subtitle="Conheça nossa Visão!"
              text="Nossa visão é.."
            />
            <CardAbout
              title="Valores"
              subtitle="Conheça nossos Valores!"
              text="Seguimos 3 valores principais"
            />
          </div>
        </div>
        <div className={styles.historia}>
          <p className={styles.title}>Equipe</p>
          <p>
            Equipe profissional, treinada e capacitada para agir em diversos
            tipos de ambiente
          </p>
        </div>
        <div className={styles.historia}>
          <p className={styles.title}>Parceiros</p>
          <p>Confira nossos parceiros e clientes!</p>
        </div>
        <div className={styles.historia}>
          <p className={styles.title}>Localização</p>
          <p>Travessa José Bastos 79</p>
        </div>
        {/*Aqui chamamos o componente footer, que será utilizado em todas as páginas da aplicação*/}
        <Footer />
      </main>
    </div>
  );
}
